name: SFCalc
main: io.github.seggan.sfcalc.SFCalc
version: ${version}
author: Seggan
depend: [Slimefun]
api-version: 1.15

commands:
  sfcalc:
    description: Base SFCalc command
    usage: "Usage: /sfcalc calc <item> [amount]"
    aliases:
      - sfc